 name: ArchCoreSystem
author: GamerXzavier
main: ARCHCore\Main
api: [2.0.0]
version: 1#Beta
commands:
 help:
  usage: /help or /?
  description: Help Command
 news:
  description: See Newss!!

  permissions:
    N.F.D:
      description: User Doesnt Have Falling Damage Events.
      default: true
    Fire.Bows:
       description: Now Player Fire Some Flame Arrows!
       default: true
