

# Config For ARCore

# Note: Do Not Delete Any '#' , Unless Its State So.

currency:
  # available currency: ARCore's currency, EconomyS
  # prefix: arcc = ARCore's Currency, eco = EconomyS
  # example:
     # api: arcc
     # api: eco
  # default use: arcc
  api: arcc

# Note To Me: Class's Skills Would'nt Include In Level Feature Cause Player Can Only Advance To Other Branch Class By Doin Quest Or Triggered An Event.
# Spoiled Next Feature Todo LoL...
Enable%Level: true
Level:
  # eg: if in level 1, the maxexp is 100, then in level 2, 100*2, then level 3, 200*2, ... 
  # Multiplier Must Be Greater Or Same From 2. Else 2 Will Be Set As Default.
  MultipleExpPerLevel: 2
  # Plus Max Exp Is For Like Example, If Level Up, It Will Undergo 100*(multiplier)+(PlusMaxExp). Leve it 0 if you dont want to add anything.
  PlusMaxExp: 0
  # add to set difficulty
  Max%Level: 150
  

Enable%FGC: true
FGC:
  # there is 3 available feature: Faction, Guild, Clan
  # put Guild as default
  # Please Put It Without Changing Anything, For Example: Faction
  # If You Put It As : faction // It Would Not Give You This Feature But Would Automatically Set Guild As Default.
  Feature: Guild

message:
  # Default Language: eng
  # Available Language: eng
  lang: eng
template:
  # Default Language: eng
  # Available Language: eng
  lang: eng
auths:
  # Default Language: eng
  # Available Language: eng
  lang: eng

# Please Look Here To Enable Some Setting
Enable%Set%Server%Name: true
Enable%Load%Default%World: true
Enable%Inventories%Saver: false
Enable%Hud: false
Enable%Pets: false
Enable%Anti%Hack: false
Enable%Chat%Filter: true
Enable%Particle: false
Enable%Set%Player%Food%Bar%On%Join: true
Enable%Set%Max%Player%Health%On%Join: true
Enable%Set%Player%Health%On%Join: true
Enable%Set%Player%Movement%Speed%On%Join: true
Enable%Set%Player%Game$Mode%To%Survival: true
Enable%Operator%To%Bypass%Force%Gamemode: false
Enable%Hub%Spawn: true
Enable%Drop%Death%Chance: false
Enable%No%Void: true
Enable%Gain%Coins%From%PK: false

# Config .. Working On It...
Setting:
  Server%Name: "Server Name"
  Load%Default%World: "World Name"
  Set%Player%Food%Bar%On%Join: 20000
  Set%Max%Player%Health%On%Join: 20
  Set%Player%Health%On%Join: 20
  Set%Player%Food%Bar%On%Respawn: 20000
  Set%Max%Player%Health%On%Respawn: 20
  Set%Player%Health%On%Respawn: 40
  Set%Player%Movement%Speed%On%Join: 0.12
  Drop%Death%Chance%Item: "388"
  No%Void%Set%Player%Max%Health: 1
  No%Void%Set%Player%Health: 1
  No%Void%Set%Player%Food: 200000
  Gain%Coins%From%PK: 20
  Lost%Coins%From%Pked: 10

NoVoid:
  Y-NoVoid: 7
  # Note: Only For One World, Why? Because.... 'You See It Yourself.'
  NoVoid%World: World Name

# Inventories Saver Setting...
Inventories:
  Saver:
    World%Name:
    - World Name
    # Remove The '#' Before The '-' And Add Your World Name To Enable This.
    #-
    #-
    #-

# Below This Is For The Function To Disable Some Events Like: Disable Player From Sleep!!
Disable:
  Use%Of%Bed: false
  Use%Of%Hunger: true
  Hunger%World:
  - World Name
  Bed%World:
  - World Name
  # - Second World Name... // Same As Above

# If Enable Pets
# Set Price
"BlazePrices" => 1000,
        "PigPrices" => 1000,
		"ChickenPrices" => 1000,
        "WolfPrices" => 1000,
	    "RabbitPrices" => 1000,
        "MagmaPrices" => 1000,
        "BatPrices" => 1000,
    	"SilverfishPrices" => 1000,
	    "SpiderPrices" => 1000,
        "CowPrices" => 1000,
		"CreeperPrices" => 1000,
		"IronGolemPrices" => 1000,
        "HuskPrices" => 1000,
	    "EndermanPrices" => 1000,
        "SheepPrices" => 1000,
        "WitchPrices" => 1000,
        "BlockPrices" => 1000,
		));